#!/bin/bash
# Billplz Webhook 一键配置脚本
# 由于 Billplz 需要网页登录，请按照以下步骤手动配置

echo "========================================"
echo "  Billplz Webhook 配置助手"
echo "========================================"
echo ""
echo "📋 配置信息（已准备好，直接复制使用）"
echo ""
echo "🔗 Webhook URL:"
echo "https://uziseller-uzi-seller.vercel.app/api/billplz-webhook"
echo ""
echo "========================================"
echo ""
echo "🚀 配置步骤（3 分钟完成）"
echo ""
echo "1️⃣  打开 Billplz 配置页面"
echo "   👉 https://www.billplz.com/enterprise/settings/webhooks"
echo ""
echo "2️⃣  点击 'Add Webhook' 或 'Create New Webhook'"
echo ""
echo "3️⃣  填写以下信息："
echo "   • Webhook URL: https://uziseller-uzi-seller.vercel.app/api/billplz-webhook"
echo "   • Signature Method: ✅ 选择 'X Signature'"
echo "   • Events: ✅ bill.paid ✅ bill.failed"
echo "   • Collection (可选): 0uklil7m"
echo ""
echo "4️⃣  点击 'Test Webhook'"
echo "   ✅ 返回 200 或 401 都是正常的"
echo ""
echo "5️⃣  点击 'Save' 保存配置"
echo ""
echo "========================================"
echo ""
echo "✅ 配置完成后的验证"
echo ""
echo "访问: https://uziseller.com"
echo "提交测试订单并完成支付"
echo "检查订单状态是否自动更新"
echo ""
echo "========================================"
echo ""
echo "📞 需要帮助？"
echo "查看详细文档: WEBHOOK-CONFIG.md"
echo ""
